server:
  port: 8080
spring:
  application:
    #应用的名称，可选
    name: reggie_take_out
  #数据源的配置
  datasource:
    druid:
      driver-class-name: com.mysql.cj.jdbc.Driver
#      linux环境下
#      url: jdbc:mysql://192.168.67.100:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
#      username: root
#      password: root

#     windows环境下
      url: jdbc:mysql://localhost:3306/reggie?serverTimezone=Asia/Shanghai&useUnicode=true&characterEncoding=utf-8&zeroDateTimeBehavior=convertToNull&useSSL=false&allowPublicKeyRetrieval=true
      username: root
      password: root
  redis:
#    host: 192.168.67.100
    host: 127.0.0.1
    port: 6379
#    password: root
    database: 0
  cache:
    redis:
      time-to-live: 1800000 #设置缓存数据的过期时间

mybatis-plus:
  configuration:
    #eg：address_book---->AddressBook;属性：user_name---->userName
    #在映射实体或者属性时，将数据库中表名和字段名中的下划线去掉，按照驼峰命名法映射
    map-underscore-to-camel-case: true
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  global-config:
    db-config:
      id-type: ASSIGN_ID

reggie:
#  path: /usr/local/javaapp/reggie_img/
  path: D:\Study\JAVA\reggie_img\